services:
  api:
    image: mcu-movies/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.backend.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend"
      - "DOMAIN=${DOMAIN}"

  frontend:
    image: mcu-movies/frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=!PathPrefix(`/api`)"
      - "DOMAIN=${DOMAIN}"

  traefik:
    image: "traefik:v2.10"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.constraints=Label(`DOMAIN`, `${DOMAIN}`)"
    ports:
      - "${PORT}:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "DOMAIN=${DOMAIN}"
