name: CI/CD
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "7"
      - run: "git branch --track main origin/main"
      # - uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: pnpm install

      - run: pnpm exec nx format:check
      - run: pnpm exec nx run-many -t lint --parallel=3
      - run: pnpm exec nx run-many -t test --parallel=3 --configuration=ci
      - run: pnpm exec nx run-many -t build --parallel=3
      - run: pnpm exec nx run-many -t docker-build --parallel=3

      - run: |
          for image in $(docker images --format "{{.Repository}}" | grep mcu-movies); do
            name=$(echo $image | sed 's/\//-/g')
            docker save $image -o $name.tar
          done
      - name: Upload images
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: |
            *.tar
